version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    restart: always
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow_new.db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - prometheus

volumes:
  grafana-data:
  prometheus-data: